version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "hantsy"
    assignees:
      - "hantsy"
    labels:
      - "dependencies"
      - "maven"
    ignore: 
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "org.springframework.cloud:spring-cloud-dependencies"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "au.com.dius:pact-jvm-provider-spring_2.12"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "au.com.dius:pact-jvm-consumer-junit_2.12"
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]  
      - dependency-name: "com.github.tomakehurst:wiremock-standalone"  
        update-types: [ "version-update:semver-major", "version-update:semver-minor"]  
      - dependency-name: "*"  
        update-types: [ "version-update:semver-major"]    
        
  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "hantsy"
    assignees:
      - "hantsy"
    labels:
      - "dependencies"
      - "npm"
    ignore: 
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]  
